[workspace]
members  = ["llama_sys"]
resolver = "2"

[package]
name    = "demesne"
version = "0.1.0"
edition = "2021"
publish = false

[features]
rocm      = ["llama_sys/rocm"]
cuda      = ["llama_sys/cuda"]
force_mmq = ["llama_sys/force_mmq"]

[dependencies]
llama_sys          = { path = "llama_sys" }
petgraph           = "0.6.5"
structopt          = "0.3.26"
futures            = "0.3.30"
tracing            = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
rocket             = { version = "0.5.0", features = ["json"] }
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1.0.26"
either             = "1.12.0"
thiserror          = "1.0.61"
