format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Lower"
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
struct_lit_width = 30
comment_width = 110
